# Generated by Django 2.1.5 on 2019-03-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utility', '0003_apilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('photograph', models.ImageField(null=True, upload_to='media/images/readers/photographs')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Gender')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Region')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Readers',
                'verbose_name': 'Reader',
            },
        ),
    ]
