# Generated by Django 2.1.5 on 2019-03-26 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190325_1112'),
        ('readers', '0002_markasread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markasread',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='markasread',
            name='region',
        ),
        migrations.AddField(
            model_name='markasread',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogPost'),
        ),
        migrations.AddField(
            model_name='markasread',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readers.Reader'),
        ),
    ]
