# Generated by Django 2.1.5 on 2019-03-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(null=True, upload_to='media/images/blogs/thumbnails')),
                ('frontend_score', models.IntegerField()),
                ('backend_score', models.IntegerField()),
                ('setup_score', models.IntegerField()),
                ('reactdj_score', models.IntegerField()),
                ('publish_date', models.DateField()),
                ('noteworthy', models.BooleanField(default=False)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Difficulty')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
