# Generated by Django 2.1.5 on 2019-03-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static/images/blogs'),
        ),
    ]
