# Generated by Django 2.1.5 on 2019-03-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190330_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/blogs'),
        ),
    ]
